name: LynxLib
version: '1.03'
main: com.lynxdeer.lynxlib.LynxLib
api-version: '1.19'
authors: [Lynxdeer]
description: General Library for all of lynx's stuff.
load: STARTUP
softdepend: [ ProtocolLib ]
commands:
  lynxlib:
    description: Various lynxlib admin commands.
    aliases: ll
    permission: op
    permission-message: I've travelled the whole world. Since I turned 18, I've visited almost every place on the planet. Every landmark, every jungle, every forest. And in all my travels, I could not find... your permission for this command.
  worlds:
    description: Worlds command.
    aliases: world
    permission: op
    permission-message: I've travelled the whole world. Since I turned 18, I've visited almost every place on the planet. Every landmark, every jungle, every forest. And in all my travels, I could not find... your permission for this command.